main: Main.o Militar.o NodoArbol.o
	g++ Main.o Militar.o NodoArbol.o -o main.out
Main.o: Main.cpp
	g++ -c Main.cpp
Militar.o: Militar.cpp Militar.h
	g++ -c Militar.cpp
NodoArbol.o: NodoArbol.cpp NodoArbol.h
	g++ -c NodoArbol.cpp